// sveltekit/src/routes/arcjet-challenge-accepted/+page.svelte
<script lang="ts">
  import RateLimited from "../../components/RateLimited.svelte";
  import NotRateLimited from "../../components/NotRateLimited.svelte";
  /**
   * Complete the challenge and use Arcjet to set the value of rateLimited to true
   * when the user has been rate limited.
   */
  // Arcjet code goes here...

  export let data: { rateLimited: boolean };
</script>

<svelte:head>
  <title>Arcjet Challenge Accepted</title>
</svelte:head>

<h1>Arcjet Challenge Accepted!</h1>

{#if data.rateLimited}
  <RateLimited />
{:else}
  <NotRateLimited />
{/if}

// nextjs/src/app/arcjet-challenge-accepted/page.tsx
import NotRateLimited from "@/components/NotRateLimited";
import RateLimited from "@/components/RateLimited";

export default function ArcjetChallenge() {
  /**
   * Complete the challenge and use Arcjet to set the value of limited to true
   * when the user has been rate limited.
   */
  // Arcjet code goes here...
  const limited = false;

  // We include the correct component based on the value of limited
  const content = limited ? <RateLimited /> : <NotRateLimited />;

  return (
    <>
      <h1>Arcjet Challenge Accepted!</h1>
      {content}
    </>
  );
}
